export const FETCH_PAYMENT_REQUEST = "FETCH_PAYMENT_REQUEST";
export const FETCH_PAYMENT_SUCCESS = "FETCH_PAYMENT_SUCCESS";
export const FETCH_PAYMENT_FAILURE = "FETCH_PAYMENT_FAILURE";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const FETCH_ORDER_INFO = "FETCH_ORDER_INFO";
