export const FETCH_PAYMENT_DETAILS_REQUEST = "FETCH_PAYMENT_DETAILS_REQUEST";
export const FETCH_PAYMENT_DETAILS_SUCCESS = "FETCH_PAYMENT_DETAILS_SUCCESS";
export const FETCH_PAYMENT_DETAILS_FAIL = "FETCH_PAYMENT_DETAILS_FAIL";
